export const data = [
  {
    id: 1,
    img: "https://cdn-a.william-reed.com/var/wrbm_gb_food_pharma/storage/images/publications/food-beverage-nutrition/dairyreporter.com/article/2020/03/16/clover-sonoma-debuts-fully-renewable-plant-based-milk-carton/10805672-1-eng-GB/Clover-Sonoma-debuts-fully-renewable-plant-based-milk-carton_wrbm_large.jpg",
    title: "Clover Sonoma Milk",
    price: 2.5,
    location: "FairPrice Shop, 150 Silat Ave, #01-44, Singapore 160150",
    date: "22 June",
  },
  {
    id: 2,
    img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/11898581_LXL1_20201021.jpg",
    title: "FairPrice Full Cream Fresh Milk",
    price: 1.65,
    location:
      "NTUC FairPrice, 78A Telok Blangah Street 32, #01-01/02, Singapore 101078",
    date: "31 May",
  },
  {
    id: 3,
    img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/13131750_XL1.jpg",
    title: "FairPrice Fresh Milk Australia",
    price: 2.95,
    location:
      "Giant Express - Redhill Close, Redhill Cl, #01-610 Block 86, Singapore 150086",
    date: "15 May",
  },
  {
    id: 4,
    img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/11898629_XL1_20210506.jpg",
    title: "FairPrice UHT Skim Milk",
    price: 1.75,
    location:
      "NTUC FairPrice, 1 Lower Kent Ridge Road, #02-16, One@KentRidge, Singapore 119082",
    date: "20 May",
  },
  {
    id: 5,
    img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/12408855_RXL1_20201130.jpg",
    title: "FairPrice Low Fat Fresh Milk",
    price: 1.8,
    location: "Pick&Go, 31 Prince George's Park, Singapore 118427",
    date: "10 January",
  },
  {
    id: 6,
    img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/458564_XL1.jpg",
    title: "NTUC FairPrice Farmhouse Fresh Milk",
    price: 3.3,
    location: "Nanyang Mart Pte Ltd, 50K Faber Heights, Singapore 129204",
    date: "23 March",
  },
  {
    id: 7,
    img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/L/260050_L1.jpg?q=60",
    title: "F&N Magnolia UHT Milk - Super Slim",
    price: 2.5,
    location: "FairPrice Finest, 111 Somerset Rd, Singapore 238164",
    date: "4 June",
  },
  {
    id: 8,
    img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/L/13103367_L1.jpg?q=60",
    title: "FairPrice Hi Calcium Fresh Soya Milk - Reduced Sugar",
    price: 1.75,
    location:
      "Jurong Provision Shop, 218 Pasir Panjang Rd, #01-09 Icon@Pasir Panjang, Singapore 118579",
    date: "10 May",
  },
  {
    id: 9,
    img: "https://media.nedigital.sg/fairprice/fpol/media/images/product/XL/10238055_XL1_20210430.jpg",
    title: "Meiji Fresh Milk Regular 2L",
    price: 5.95,
    location: "Little Farms, 491 River Valley Rd, #01-20, Singapore 248371",
    date: "20 April",
  },
  {
    id: 10,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxuZBKlBUSlgPYRGg9JK3FyZLx3TI3mIPyMv2PvRjsA5RR462JKWKvy7leXxRXOFviyn93_p5a&usqp=CAc",
    title: "Marigold HL Milk - Chocolate",
    price: 3.2,
    location: "Leo's Indian Grocery Shop, 126C Kim Tian Rd, Singapore 160116",
    date: "18 February",
  },
];
